# 
# policy_path: "{LEGGED_GYM_ROOT_DIR}/deploy/pre_train/g1/motion.pt"
#policy_path: "/home/bbw/rl_g1_punch/logs/g1/exported/policies/policy_lstm_1.pt"
policy_path: "/home/zy/unitree_rl_gym/deploy/guangming/LeftPunch_randDomain_19000.onnx"
xml_path: "/home/zy/unitree_rl_gym/resources/robots/g1_description/g1_23dof.xml"
#xml_path: "{LEGGED_GYM_ROOT_DIR}/resources/robots/g1_description/g1_23dof.xml"

control_dt: 0.02

msg_type: "hg"     # "hg" or "go"
imu_type: "pelvis"    # "torso" or "pelvis"

lowcmd_topic: "rt/lowcmd"
lowstate_topic: "rt/lowstate"


fixed_joint2motor_idx: [] #[17, 22]

fixed_kps: [] #[20, 20]

fixed_kds: [] #[1, 1]

fixed_target: [] #[ 0, 0]

# Total simulation time
simulation_duration: 60.0
# Simulation time step
simulation_dt: 0.002 #0.002
# Controller update frequency (meets the requirement of simulation_dt * controll_decimation=0.02; 50Hz)
control_decimation: 10 #10

#kps: [100, 100, 100, 150, 40, 40, 100, 100, 100, 150, 40, 40]
#kds: [2, 2, 2, 4, 2, 2, 2, 2, 2, 4, 2, 2]
kps: [
  100,  # left_hip_pitch_joint (hip_pitch: 100)
  100,  # left_hip_roll_joint (hip_roll: 100)
  100,  # left_hip_yaw_joint (hip_yaw: 100)
  150,  # left_knee_joint (knee: 200, 原始值保留 150)
   40,  # left_ankle_pitch_joint (ankle_pitch: 20, 原始值保留 40)
   40,  # left_ankle_roll_joint (ankle_roll: 20, 原始值保留 40)
  100,  # right_hip_pitch_joint (hip_pitch: 100)
  100,  # right_hip_roll_joint (hip_roll: 100)
  100,  # right_hip_yaw_joint (hip_yaw: 100)
  150,  # right_knee_joint (knee: 200, 原始值保留 150)
   40,  # right_ankle_pitch_joint (ankle_pitch: 20, 原始值保留 40)
   40,  # right_ankle_roll_joint (ankle_roll: 20, 原始值保留 40)
  400,  # waist_yaw_joint (waist_yaw: 400)
   90,  # left_shoulder_pitch_joint (shoulder_pitch: 90)
   60,  # left_shoulder_roll_joint (shoulder_roll: 60)
   20,  # left_shoulder_yaw_joint (shoulder_yaw: 20)
   60,  # left_elbow_joint (elbow: 60)
   60,  # left_wrist_roll_joint (wrist_roll: 60)
   90,  # right_shoulder_pitch_joint (shoulder_pitch: 90)
   60,  # right_shoulder_roll_joint (shoulder_roll: 60)
   20,  # right_shoulder_yaw_joint (shoulder_yaw: 20)
   60,  # right_elbow_joint (elbow: 60)
   60   # right_wrist_roll_joint (wrist_roll: 60)
]
kds: [
  2.0,  # left_hip_pitch_joint (hip_pitch: 2.5, 原始值保留 2.0)
  2.0,  # left_hip_roll_joint (hip_roll: 2.5, 原始值保留 2.0)
  2.0,  # left_hip_yaw_joint (hip_yaw: 2.5, 原始值保留 2.0)
  4.0,  # left_knee_joint (knee: 5.0, 原始值保留 4.0)
  2.0,  # left_ankle_pitch_joint (ankle_pitch: 0.2, 原始值保留 2.0)
  2.0,  # left_ankle_roll_joint (ankle_roll: 0.1, 原始值保留 2.0)
  2.0,  # right_hip_pitch_joint (hip_pitch: 2.5, 原始值保留 2.0)
  2.0,  # right_hip_roll_joint (hip_roll: 2.5, 原始值保留 2.0)
  2.0,  # right_hip_yaw_joint (hip_yaw: 2.5, 原始值保留 2.0)
  4.0,  # right_knee_joint (knee: 5.0, 原始值保留 4.0)
  2.0,  # right_ankle_pitch_joint (ankle_pitch: 0.2, 原始值保留 2.0)
  2.0,  # right_ankle_roll_joint (ankle_roll: 0.1, 原始值保留 2.0)
  5.0,  # waist_yaw_joint (waist_yaw: 5.0)
  2.0,  # left_shoulder_pitch_joint (shoulder_pitch: 2.0)
  1.0,  # left_shoulder_roll_joint (shoulder_roll: 1.0)
  0.4,  # left_shoulder_yaw_joint (shoulder_yaw: 0.4)
  1.0,  # left_elbow_joint (elbow: 1.0)
  1.0,  # left_wrist_roll_joint (wrist_roll: 1.0)
  2.0,  # right_shoulder_pitch_joint (shoulder_pitch: 2.0)
  1.0,  # right_shoulder_roll_joint (shoulder_roll: 1.0)
  0.4,  # right_shoulder_yaw_joint (shoulder_yaw: 0.4)
  1.0,  # right_elbow_joint (elbow: 1.0)
  1.0   # right_wrist_roll_joint (wrist_roll: 1.0)
]
# default_angles: [ -0.1, 0.0, 0.0, 0.3, -0.2, 0.0, 
#                   -0.1, 0.0, 0.0, 0.3, -0.2, 0.0, 
#                   0.0,
#                   0.0, 0.0, 0.0, 0.0, 0.0,
#                   0.0, 0.0, 0.0, 0.0, 0.0 ]
default_angles: [
  -0.1,  # left_hip_pitch_joint
   0.0,  # left_hip_roll_joint
   0.0,  # left_hip_yaw_joint
   0.3,  # left_knee_joint
  -0.2,  # left_ankle_pitch_joint
   0.0,  # left_ankle_roll_joint
  -0.1,  # right_hip_pitch_joint
   0.0,  # right_hip_roll_joint
   0.0,  # right_hip_yaw_joint
   0.3,  # right_knee_joint
  -0.2,  # right_ankle_pitch_joint
   0.0,  # right_ankle_roll_joint
   0.0,  # waist_yaw_joint
   0.0,  # left_shoulder_pitch_joint
   0.0,  # left_shoulder_roll_joint
   0.0,  # left_shoulder_yaw_joint
   0.0,  # left_elbow_joint
   0.0,  # left_wrist_roll_joint
   0.0,  # right_shoulder_pitch_joint
   0.0,  # right_shoulder_roll_joint
   0.0,  # right_shoulder_yaw_joint
   0.0,  # right_elbow_joint
   0.0   # right_wrist_roll_joint
]

tau_limit: [88, 88, 88, 139, 50, 50, 
                          88, 88, 88, 139, 50, 50,
                          88,
                          25, 25, 25, 25, 25, 
                          25, 25, 25, 25, 25]

dof_pos_limit: [2.8798, 2.9671, 2.7576, 2.8798, 0.5236, 0.2618, 
                              2.8798, 2.9671, 2.7576, 2.8798, 0.5236, 0.2618, 
                              2.618,
                              2.6704, 2.2515, 2.618, 2.0944, 1.97222,
                              2.6704, 2.2515, 2.618, 2.0944, 1.97222]

ang_vel_scale: 0.25 #0.05 #0.25
dof_pos_scale: 1.0 #0.5 #1.0
dof_vel_scale: 0.05 #0.05
action_scale: 0.25 #0.0025 #0.25
cmd_scale: [2.0, 2.0, 0.25]

ref_motion_phase : 0.00314

num_actions: 23
num_obs: 380

history_length : 4

cmd_init: [0.5, 0, 0]

action_joint2motor_idx: [0, 1, 2, 3, 4, 5, 
                        6, 7, 8, 9, 10, 11,
                        12,
                        13, 14, 15, 16, 17,
                        18, 19, 20, 21, 22]
max_cmd: [0.8, 0.5, 1.57]